# Generated by Django 6.1.1 on 2026-09-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='learning_goals',
            field=models.TextField(blank=True),
        ),
    ]
