# Generated by Django 6.1.1 on 2026-09-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TUTOR', 'Tutor'), ('STUDENT', 'Student')], db_index=True, default='STUDENT', max_length=10),
        ),
    ]
